### PR TITLE
Add qr code monster controlnets

### LINKED ISSUE #109: Is there a way to use qrcode_monster in  animatediff-cli-prompt-travel ?
https://huggingface.co/monster-labs/control_v1p_sd15_qrcode_monster

### PR DESCRIPTION
**Pull request by JCBrouwer**
Two ControlNet's of MrUgleh/IllusionDiffusion fame.

Can be enabled like any other ControlNet by adding control images to the correct folder and enabling in the controlnet_map section of the config.

https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/15871226/4c57140f-f653-4dbb-97d4-5def49805c2a

Closes #109

### CODE REVIEW

**Comment by ShmuelRonen** [comment]
Can you add to prompt_travel.json the use of qrcode_monster please

**Comment by JCBrouwer** [comment]
It's the same as all the other ControlNet models. Put your control images numbered by frame (e.g. 0000.png, 0016.png) in either `data/controlnet_image/test/qr_code_monster_v1` or `data/controlnet_image/test/qr_code_monster_v2` and then add a corresponding section to the 'controlnet_map' in the config:
```json
    "controlnet_map": {
       ...
        "qr_code_monster_v2": {
            "enable": false,
            "use_preprocessor": true,
            "preprocessor": {"type": "none", "param": {}},
            "guess_mode": false,
            "controlnet_conditioning_scale": 0.4,
            "control_guidance_start": 0.0,
            "control_guidance_end": 1.0,
            "control_scale_list": [0.5, 0.4, 0.3, 0.2, 0.1],
        }
    }
```

**Comment by ShmuelRonen** [comment]
Thanks! it works. But I got little effect of the mask on the video. How can the effect be increased?

**Comment by ShmuelRonen** [comment]
https://www.facebook.com/reel/1043131240150005

Here I use this masks but thr effect is not clear

mask1

**Comment by ShmuelRonen** [comment]
What are the preprocessor type options other than 'none'?

...
"qr_code_monster_v2":{
	  "enable": true,
      "use_preprocessor": true,
      "preprocessor":{
		  "type": "none",
		  "param": {}},
      "guess_mode": false,
      "controlnet_conditioning_scale": 1,
      "control_guidance_start": 0.13,
      "control_guidance_end": 0.75,
      "control_scale_list": [1, 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1]
    },
...

**Comment by JCBrouwer** [comment]
You can find the list of preprocessors here: https://github.com/s9roll7/animatediff-cli-prompt-travel/blob/main/src/animatediff/generate.py#L233

In general you must use the preprocessor that the ControlNet was trained with for the best results.

However, there is definitely room for creative experimentation. For example, the QR ControlNet was trained on black and white QR code images, so you could write a preprocessor that binarizes images to black and white and then try out photos or drawings instead.

**Comment by ShmuelRonen** [comment]
If I want to choose the preprocessor 'invert' like on automatic1111 how can I do it?
If I write "preprocessor":{
		  "type": "invert",

It's make an error.

Preprocessor

**Comment by ShmuelRonen** [comment]
So the 'build-in' pre-processors are: "lineart_anime", "openpose_full", "softedge_hedsafe", "shuffle", "depth_midas", "canny", "lineart_realistic", "mlsd", "normal_bae", "scribble_pidsafe", "upernet_seg"
And also:
"dwpose", "upernet_seg", "blur", "tile_resample", and "none" 

Am I right?

**Pull request merged**
